### ISSUE TITLE
Installation fails for 0.2.5

### ISSUE THREAD

**Issue by jamespenick** [samselikoff/ember-cli-mirage#1007]
I can't seem to install the latest version of mirage. Here's what I'm seeing:

ember install ember-cli-mirage@0.2.5
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
/home/jpenick/git/ui/node_modules/ember-cli-mirage/blueprints/ember-cli-mirage/index.js:35
    }).then(() => {
             ^
Unexpected token )
/home/jpenick/git/ui/node_modules/ember-cli-mirage/blueprints/ember-cli-mirage/index.js:35
    }).then(() => {
             ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Blueprint.load (/home/jpenick/git/ui/node_modules/ember-cli/lib/models/blueprint.js:1276:29)
    at Function.Blueprint.lookup (/home/jpenick/git/ui/node_modules/ember-cli/lib/models/blueprint.js:1253:24)
    at CoreObject.module.exports.Task.extend.lookupBlueprint (/home/jpenick/git/ui/node_modules/ember-cli/lib/tasks/generate-from-blueprint.js:89:22)
jpenick@jpenick-linux:~/git/ui$ ember --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.8.0
node: 0.12.15
os: linux x64

Note that everything installs fine when I do ember install ember-cli-mirage@0.2.4

**Comment by jamespenick** [comment]
Never mind. It looks like the failure was related to my old version of node. I updated to a more current version and the installation worked. Sorry for the noise.
