### ISSUE TITLE
"Model not registered" error when dasherized factory uses `association`

### ISSUE THREAD

**Issue by pgengler** [samselikoff/ember-cli-mirage#1076]
When a dasherized factory (e.g., `mirage/factories/book-entry.js`) references a `belongsTo` association using `.association` (e.g., `user: association()`), execution stops with this error:

```
ember.debug.js:18008 Error: Model not registered: book-entry
    at Server._fetchAssociationNameFromModel (https://addons.ember-twiddle.com/ember-2.12.0/ember-cli-mirage/0.3.0/addon.js:60256:17)
    at https://addons.ember-twiddle.com/ember-2.12.0/ember-cli-mirage/0.3.0/addon.js:60240:40
    at Array.forEach (native)
    at Server._mapAssociationsFromAttributes (https://addons.ember-twiddle.com/ember-2.12.0/ember-cli-mirage/0.3.0/addon.js:60238:12)
    at Server.build (https://addons.ember-twiddle.com/ember-2.12.0/ember-cli-mirage/0.3.0/addon.js:59858:16)
    at Server.create (https://addons.ember-twiddle.com/ember-2.12.0/ember-cli-mirage/0.3.0/addon.js:59908:32)
    at Server.createList (https://addons.ember-twiddle.com/ember-2.12.0/ember-cli-mirage/0.3.0/addon.js:59953:33)
    at Object.exports.default (about:srcdoc:84:12)
    at Server.config (https://addons.ember-twiddle.com/ember-2.12.0/ember-cli-mirage/0.3.0/addon.js:59676:39)
    at new Server (https://addons.ember-twiddle.com/ember-2.12.0/ember-cli-mirage/0.3.0/addon.js:59626:12)
```

Ember Twiddle: https://ember-twiddle.com/8f5ffea94079cd9fe8e69d41eb1ef967 (look in the browser console for the error, and observe that nothing appears in the 'output' section).

The twiddle uses mirage 0.3.0; this same behavior is occurring with 0.3.1.

**Comment by darylalexjohnson** [comment]
@pgengler - Could you have a look at this PR and see if it resolves your issue?

**Comment by pgengler** [comment]
@darylalexjohnson Seems like it does.

**Comment by darylalexjohnson** [comment]
@samselikoff Do have time for any feedback on this?

**Comment by bartocc** [comment]
This seems to be fixed by #1170, so I believe this issue could be closed.
A new release needs to be cut though. Any plans on this ?

**Comment by mellatone** [comment]
+1

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/pull/1170 closes
