### ISSUE TITLE
invalid regular expression: /"predef" on install

### ISSUE THREAD

**Issue by av-guy** [samselikoff/ember-cli-mirage#1234]
`installing ember-cli-mirage
  create \mirage\config.js
  create \mirage\scenarios\default.js
  create \mirage\serializers\application.js
Invalid regular expression: /"predef": [
/: Unterminated character class
SyntaxError: Invalid regular expression: /"predef": [\n
/: Unterminated character class
    at String.match (native)
    at insertIntoFile (C:\Users\dev\ember\super-rentals\node_modules\ember-cli\lib\utilities\insert-into-file.js:90:39)
    at Class.insertIntoFile (C:\Users\dev\ember\super-rentals\node_modules\ember-cli\lib\models\blueprint.js:1175:12)
    at Class.insertServerIntoJSHintrc (C:\Users\dev\ember\super-rentals\node_modules\ember-cli-mirage\blueprints\ember-cli-mirage\index.js:50:17)
    at insertServerIntoESLintrc.then (C:\Users\dev\ember\super-rentals\node_modules\ember-cli-mirage\blueprints\ember-cli-mirage\index.js:75:19)
    at tryCatcher (C:\Users\dev\ember\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:329:19)
    at invokeCallback (C:\Users\dev\ember\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:507:31)
    at publish (C:\Users\dev\ember\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:493:7)
    at flush (C:\Users\dev\ember\super-rentals\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2432:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)`

I keep getting this when trying ember install ember-cli-mirage. If this is not an appropriate question or issue, I apologize. I just didn't know where else to reach out for help.

**Comment by av-guy** [comment]
#7475 fixes this issue
