### ISSUE TITLE
Build Error (broccoli-persistent-filter:EslintValidationFilter) in mirage/config.js

### ISSUE THREAD

**Issue by beerlington** [samselikoff/ember-cli-mirage#1399]
Hey! Our team has run into this a few times and my google skills are failing me so I wanted to just open an issue in case anyone else runs into this.

Basically after installing mirage in a barebones ember app using eslint, it will no longer boot.

We get the following error:

```
~/code/mirage-build-error(master ✗) ember s
Build Error (broccoli-persistent-filter:EslintValidationFilter) in mirage/config.js

ENOENT: no such file or directory, scandir '/Users/peterbrown/code/mirage-build-error/mirage/mirage'


Stack Trace and Error Report: /var/folders/00/cnxym0wj0xs99j7x1hc12d8w0000gn/T/error.dump.fd7024b25d9a2f9dc1894b21d55cf0c9.log
```

I have a public repo where you can see the issue - https://github.com/beerlington/mirage-build-error

The first commit in the repo boots the app fine. The second commit adds mirage and then no longer boots.

## The fix for this is to add the following to `.eslintignore`:

```
/mirage/mirage
```
and then the server boots.

Just for search purposes, the full stack trace of the error is:

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, scandir '/Users/peterbrown/code/mirage-build-error/mirage/mirage'
    at Object.fs.readdirSync (fs.js:904:18)
    at traverseFolder (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:32564:18)
    at findRoot (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:32580:10)
    at maybeParse (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:32592:16)
    at editorconfigSyncNoCache (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:32605:35)
    at editorconfigSyncNoCache (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:28538:20)
    at /Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:34796:14
    at Array.map (<anonymous>)
    at _resolveConfig (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:34795:40)
    at Function.resolveConfig.sync (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:34831:12)
  - codeFrame: ENOENT: no such file or directory, scandir '/Users/peterbrown/code/mirage-build-error/mirage/mirage'
  - errorMessage: mirage/config.js: ENOENT: no such file or directory, scandir '/Users/peterbrown/code/mirage-build-error/mirage/mirage'
        in /var/folders/00/cnxym0wj0xs99j7x1hc12d8w0000gn/T/broccoli-61403MQQE2vc6x3MP/out-139-funnel
        at broccoli-persistent-filter:EslintValidationFilter
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: mirage/config.js
    - line: [undefined]
    - treeDir: /var/folders/00/cnxym0wj0xs99j7x1hc12d8w0000gn/T/broccoli-61403MQQE2vc6x3MP/out-139-funnel
  - message: mirage/config.js: ENOENT: no such file or directory, scandir '/Users/peterbrown/code/mirage-build-error/mirage/mirage'
        in /var/folders/00/cnxym0wj0xs99j7x1hc12d8w0000gn/T/broccoli-61403MQQE2vc6x3MP/out-139-funnel
        at broccoli-persistent-filter:EslintValidationFilter
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: broccoli-persistent-filter:EslintValidationFilter
  - originalErrorMessage: ENOENT: no such file or directory, scandir '/Users/peterbrown/code/mirage-build-error/mirage/mirage'
  - stack: Error: ENOENT: no such file or directory, scandir '/Users/peterbrown/code/mirage-build-error/mirage/mirage'
    at Object.fs.readdirSync (fs.js:904:18)
    at traverseFolder (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:32564:18)
    at findRoot (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:32580:10)
    at maybeParse (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:32592:16)
    at editorconfigSyncNoCache (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:32605:35)
    at editorconfigSyncNoCache (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:28538:20)
    at /Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:34796:14
    at Array.map (<anonymous>)
    at _resolveConfig (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:34795:40)
    at Function.resolveConfig.sync (/Users/peterbrown/code/mirage-build-error/node_modules/prettier/index.js:34831:12)
```

**Comment by beerlington** [comment]
@samselikoff I have no idea if this is mirage-specific so feel free to close if it doesn't seem relevant. I really just wanted to open it in case we forget and start googling the error again. 🎈

**Comment by esbanarango** [comment]
I'm having the same issue here with a brand new Ember app using eslint. 🤚

**Comment by ezpuzz** [comment]
`eslint-plugin-prettier` doesn't resolve paths correctly

**Comment by samselikoff** [comment]
For now, should we add some Prettier install instructions to Mirage's docs? Trying to figure out what Mirage's responsibility is here

**Comment by samselikoff** [comment]
Looks like that paths RFC got merged for Ember CLI, so there's a longer-term fix on the way. For now I just [added some documentation to the Install step](http://www.ember-cli-mirage.com/docs/v0.4.x/installation/) that warns Prettier users to either pin the version or add the line to the ignore file

![image](https://user-images.githubusercontent.com/2922250/50739956-250ef200-11b5-11e9-972e-4475ed441a1a.png)

Closing for now, thanks everyone!
