### ISSUE TITLE
Not working with ember-fetch @ 6.4.0 and preferNative: true

### ISSUE THREAD

**Issue by scottkidder** [samselikoff/ember-cli-mirage#1448]
It seems something between ember-fetch and Pretender is no longer working now that I have upgraded from ember-fetch@5.1.3 to ember-fetch@6.4.0.

I have been using `preferNative: true` for some time as we only target browsers with support. See https://github.com/ember-cli/ember-fetch/blob/master/README.md#allow-native-fetch 

On upgrading ember-fetch I had many test failures like this:
```
        actual: >
            null
        stack: >
            Error: Ember Data Request GET /api/bars returned a 404
            Payload (text/html; charset=utf-8)
            Not found: /api/bars
                at ErrorClass.EmberError [as constructor] (http://localhost:4301/assets/vendor.js:46327:23)
                at ErrorClass.AdapterError (http://localhost:4301/assets/vendor.js:199045:17)
                at new ErrorClass (http://localhost:4301/assets/vendor.js:199063:24)
                at Class.handleResponse (http://localhost:4301/assets/vendor.js:208749:18)
                at Class.handleResponse (http://localhost:4301/assets/vendor.js:169959:19)
                at Class.superWrapper [as handleResponse] (http://localhost:4301/assets/vendor.js:40331:28)
                at Class.ajaxError (http://localhost:4301/assets/vendor.js:214168:24)
                at _ajaxRequest.catch.then.then (http://localhost:4301/assets/vendor.js:214104:22)
        message: >
            Promise rejected before "can get bars": Ember Data Request GET /api/bars returned a 404
            Payload (text/html; charset=utf-8)
            Not found: /api/bars
```

Luckily I discovered that if I set `preferNative: false` (the default), everything works correctly again. I'm not familiar with fetch or Pretender so if anyone is able to point me the right way then I'll be happy to dive in.

**Comment by samselikoff** [comment]
Thanks for the report!

Could you create a simplified reproduction with one of the following methods?

- Fork the [Mirage CodeSandox](https://codesandbox.io/s/003o6pq34n)
- Upload a repo
- Creating a PR with a failing test

**Comment by scottkidder** [comment]
I'm planning to test this with the latest pretender upgrades soon.

**Comment by scottkidder** [comment]
Everything works great on latest mirage and native fetch. :tada:

Thanks!

**Comment by samselikoff** [comment]
Awesome! Thanks for following up :)
