### ISSUE TITLE
Error in blueprint template: i is not defined

### ISSUE THREAD

**Issue by ballPointPenguin** [samselikoff/ember-cli-mirage#146]
Starting a fresh ember-cli 0.26 app, with ember 1.13.0-beta.2.
ember install ember-cli-mirage fails:
```
[~/dev/cupery-group/ember]$ ember install ember-cli-mirage
version: 0.2.6
Installed packages for tooling via npm.
installing
  create app/mirage/config.js
  create app/mirage/factories/contact.js
  create app/mirage/fixtures/contacts.js
i is not defined (Error in blueprint template: /home/brosas/dev/cupery-group/ember/node_modules/ember-cli-mirage/blueprints/ember-cli-mirage/files/app/mirage/factories/contact.js)
ReferenceError: i is not defined (Error in blueprint template: /home/brosas/dev/cupery-group/ember/node_modules/ember-cli-mirage/blueprints/ember-cli-mirage/files/app/mirage/factories/contact.js)
    at eval (eval at <anonymous> (/home/brosas/dev/cupery-group/ember/node_modules/ember-cli/node_modules/lodash/string/template.js:214:56), <anonymous>:6:10)
    at processTemplate (/home/brosas/dev/cupery-group/ember/node_modules/ember-cli/lib/models/file-info.js:13:52)
    at /home/brosas/dev/cupery-group/ember/node_modules/ember-cli/lib/models/file-info.js:94:20
    at lib$rsvp$$internal$$tryCatch (/home/brosas/dev/cupery-group/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/brosas/dev/cupery-group/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/brosas/dev/cupery-group/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/brosas/dev/cupery-group/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

**Comment by ballPointPenguin** [comment]
This could be an ember-cli bug. It's as if babel broke for addon blueprints.

**Comment by ballPointPenguin** [comment]
temporary workaround:
In node_modules/ember-cli-mirage/blueprints/ember-cli-mirage/files/app/mirage/factories/contact.js,
edit the email function to not use es6-style string interpolation and then re-run ember g ember-cli-mirage

**Comment by samselikoff** [comment]
frustrating - thanks for reporting!

c210a34a20955ac96f5d8bc0913f5aa8e2aa6634 closes.

**Comment by cdmwebs** [comment]
@samselikoff new 0.2.6 app and c210a34 didn't help. I had to remove the commented line in `node_modules/ember-cli-mirage/blueprints/ember-cli-mirage/files/app/mirage/factories/contact.js`.

**Comment by samselikoff** [comment]
tested, should be all set. thanks guys

**Comment by cdmwebs** [comment]
@samselikoff thanks!!

**Comment by corrspt** [comment]
Just want to say thanks as well @samselikoff, I tried updating to CLI 0.26 an ran into the same issue. Waiting for a new release, :+1:

**Comment by samselikoff** [comment]
@corrspt good call, just pushed 0.1.0. thanks!
