### ISSUE TITLE
`Cannot read property 'call' of undefined`

### ISSUE THREAD

**Issue by jherdman** [samselikoff/ember-cli-mirage#148]
I'm upgrading from 0.0.27 today in an Ember 1.11.0 app, and I'm receiving the following error when running my tests:

```

Source: 	
TypeError: Cannot read property 'call' of undefined
    at exports.default.loadConfig (http://es-dev.precisionnutrition.com:4200/assets/vendor.js:91196:13)
    at initialize (http://es-dev.precisionnutrition.com:4200/assets/student-app.js:2990:18)
    at http://es-dev.precisionnutrition.com:4200/assets/vendor.js:14870:11
    at http://es-dev.precisionnutrition.com:4200/assets/vendor.js:14894:9
    at visit (http://es-dev.precisionnutrition.com:4200/assets/vendor.js:12835:7)
    at DAG.topsort (http://es-dev.precisionnutrition.com:4200/assets/vendor.js:12947:11)
    at Namespace.default.extend._runInitializer (http://es-dev.precisionnutrition.com:4200/assets/vendor.js:14893:13)
    at Namespace.default.extend.runInitializers (http://es-dev.precisionnutrition.com:4200/assets/vendor.js:14865:12)
    at Namespace.default.extend.boot (http://es-dev.precisionnutrition.com:4200/assets/vendor.js:14765:12)
    at Namespace.default.extend.domReady (http://es-dev.precisionnutrition.com:4200/assets/vendor.js:14751:12)
```

As near I can tell this is Mirage telling me that it cannot load my test environment. I'm not really sure how to resolve this.

**Comment by samselikoff** [comment]
hm, so you went to 0.29?

I just pushed 0.1.0 but I don't think it would fix this.

**Comment by cball** [comment]
Apologies, this should have been added to the CHANGELOG. Add the following to the bottom of your mirage config:

```
export function testConfig() {
  // add test only routes here
}
```

**Comment by samselikoff** [comment]
@cball ah, I didn't realize this would break configs that didn't have it defined. We should make it so it's optional

**Comment by cball** [comment]
@samselikoff any ideas how to do that? Is it possible to conditionally load ES6 imports?

**Comment by samselikoff** [comment]
fix coming

**Comment by samselikoff** [comment]
the import works without the function being defined, the local var just becomes `undefined`. I wish there were a way to do conditional imports (would have simplified things earlier on for me) but I'm pretty sure there's not.

I really wish we could have an automated true end-to-end test that just starts a new ember app, installs mirage and ensures the app can build + test runner loads.
