### ISSUE TITLE
Faker.js missing

### ISSUE THREAD

**Issue by kgish** [samselikoff/ember-cli-mirage#178]
After I upgraded, I get the following error when I run `ember server`

Any ideas what may be causing this?

```
version: 0.2.7
Livereload server on port 35729
Serving on http://localhost:4200/
Path or pattern "bower_components/Faker/build/build/faker.js" did not match any files
Error: Path or pattern "bower_components/Faker/build/build/faker.js" did not match any files
    at Object.multiGlob (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/kiffin/projects/na-mockup/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)


```

**Comment by kgish** [comment]
I did the following, which seems to have fixed the problem:
```
ember install ember-faker
```

**Comment by samselikoff** [comment]
Sometimes you have to run `ember g ember-cli-mirage` to install the addon

**Comment by kgish** [comment]
Thanks, as suggested I ran `ember g ember-cli-mirage` and the problem went away.
