### ISSUE TITLE
TypeError: Cannot read property 'adapter:{{model-name}}' of undefined

### ISSUE THREAD

**Issue by isratrade** [samselikoff/ember-cli-mirage#274]
I have a model and adapter called deployment. 
I have the routes and factories set up.
All works ok for the collection route. /api/deployments
However, for the single object route /api/deployments/1, it gives this errror

```
afterEach failed on click deployment link and verify edit deployment page : Cannot read property 'adapter:deployment' of undefined@ 1878 ms
Source: 	
TypeError: Cannot read property 'adapter:deployment' of undefined
    at ember$data$lib$system$store$$Service.extend.retrieveManagedInstance (http://localhost:7357/assets/vendor.js:139763:34)
    at ember$data$lib$system$store$$Service.extend.lookupAdapter (http://localhost:7357/assets/vendor.js:139776:21)
    at ember$data$lib$system$store$$Service.extend.adapterFor (http://localhost:7357/assets/vendor.js:139693:28)
    at null.<anonymous> (http://localhost:7357/assets/vendor.js:139126:30)
    at Array.forEach (native)
    at forEach (http://localhost:7357/assets/vendor.js:26945:30)
    at ember$data$lib$system$store$$Service.extend.flushPendingSave (http://localhost:7357/assets/vendor.js:139123:9)
    at Queue.invoke (http://localhost:7357/assets/vendor.js:11464:16)
    at Object.Queue.flush (http://localhost:7357/assets/vendor.js:11528:11)
    at Object.DeferredActionQueues.flush (http://localhost:7357/assets/vendor.js:11324:17)
````
I am on Ember 1.13.10 and ember-cli 1.13 but ember-data 1-beta-16

Thanks for your help!

**Comment by blimmer** [comment]
I think this might be an issue unrelated to Mirage. It seems like it might have something to do with the adapter or store itself. Can you provide a simple example of this? Please feel free to [use my sample repo](https://github.com/blimmer/ember-cli-example-app-for-github) .

**Comment by samselikoff** [comment]
@isratrade were you able to figure this out?

**Comment by samselikoff** [comment]
Closing for now, please chime back in if this is still a problem. Thanks!
