### ISSUE TITLE
fake_xml_http_request not found

### ISSUE THREAD

**Issue by alex88** [samselikoff/ember-cli-mirage#307]
After installing ember-cli-mirage I get this error:

```
Path or pattern "bower_components/FakeXMLHttpRequest/fake_xml_http_request.js" did not match any files
Error: Path or pattern "bower_components/FakeXMLHttpRequest/fake_xml_http_request.js" did not match any files
  at Object.multiGlob (/Users/myuser/Sites/project-frontend/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:203:13)
  at Class.module.exports.CachingWriter.extend.addFiles (/Users/myuser/Sites/project-frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
  at Class.module.exports.CachingWriter.extend.updateCache (/Users/myuser/Sites/project-frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
  at /Users/myuser/Sites/project-frontend/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
  at lib$rsvp$$internal$$tryCatch (/Users/myuser/Sites/project-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/myuser/Sites/project-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/Users/myuser/Sites/project-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$asap$$flush (/Users/myuser/Sites/project-frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
```

however I don't see it as a requirement for ember-cli-mirage, could be related somehow?

**Comment by alex88** [comment]
Oh I see

    app.import(app.bowerDirectory + '/FakeXMLHttpRequest/fake_xml_http_request.js');

in the index.js file

**Comment by alex88** [comment]
Oh nvm, colleague didn't installed mirage correctly

**Comment by alex88** [comment]
Oh nvm, colleague didn't installed mirage correctly
