### ISSUE TITLE
Change factory names to not use ":"

### ISSUE THREAD

**Issue by zacstewart** [samselikoff/ember-cli-mirage#348]
After installing Mirage, I started getting this error in the console:

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: injectedFactory.reopenClass is not a function
Stack trace: TypeError: injectedFactory.reopenClass is not a function
    at factoryFor (http://localhost:5000/assets/frontend/vendor-3f28de66e3cde419f61cd9abff7b7a97.js:11949:23)
    at Object.Container.lookupFactory (http://localhost:5000/assets/frontend/vendor-3f28de66e3cde419f61cd9abff7b7a97.js:11824:14)
    at exports.default._emberRuntimeSystemObject.default.extend._nameToClass (http://localhost:5000/assets/frontend/vendor-3f28de66e3cde419f61cd9abff7b7a97.js:16549:31)
    at http://localhost:5000/assets/frontend/vendor-3f28de66e3cde419f61cd9abff7b7a97.js:16746:25
    at Array.map (native)
    at exports.default._emberRuntimeSystemObject.default.extend.getModelTypes (http://localhost:5000/assets/frontend/vendor-3f28de66e3cde419f61cd9abff7b7a97.js:16744:56)
    at exports.default._emberRuntimeSystemObject.default.extend.watchModelTypes (http://localhost:5000/assets/frontend/vendor-3f28de66e3cde419f61cd9abff7b7a97.js:16524:29)
    at getModelTypes (<anonymous>:840:55)
    at Object.apply (http://localhost:5000/assets/frontend/vendor-3f28de66e3cde419f61cd9abff7b7a97.js:34091:18)
    at Object.sendEvent (http://localhost:5000/assets/frontend/vendor-3f28de66e3cde419f61cd9abff7b7a97.js:27643:28)
```

I patched my copy of _ember.debug.js_ to inject a breakpoint when `injectedFactory.reopenClass` is not a function to see what's going on:

```javascript
  function factoryFor(container, fullName) {
    var cache = container.factoryCache;
    if (cache[fullName]) {
      return cache[fullName];
    }
    var registry = container._registry;
    var factory = registry.resolve(fullName);
    if (factory === undefined) {
      return;
    }

    var type = fullName.split(':')[0];
    if (!factory || typeof factory.extend !== 'function' || !_emberMetalCore["default"].MODEL_FACTORY_INJECTIONS && type === 'model') {
      if (factory && typeof factory._onLookup === 'function') {
        factory._onLookup(fullName);
      }

      // TODO: think about a 'safe' merge style extension
      // for now just fallback to create time injection
      cache[fullName] = factory;
      return factory;
    } else {
      var injections = injectionsFor(container, fullName);
      var factoryInjections = factoryInjectionsFor(container, fullName);

      factoryInjections._toString = registry.makeToString(factory, fullName);

      var injectedFactory = factory.extend(injections);
      if (!injectedFactory.reopenClass) {
        debugger;
      }
      injectedFactory.reopenClass(factoryInjections);

      if (factory && typeof factory._onLookup === 'function') {
        factory._onLookup(fullName);
      }

      cache[fullName] = injectedFactory;

      return injectedFactory;
    }
  }
```

And what I found was that this only occurs when a factory for `"model:mirage/factories"` is being looked up:

![screen shot 2015-10-30 at 1 07 37 pm](https://cloud.githubusercontent.com/assets/435548/10852506/7000fc02-7f07-11e5-8859-b7fbb0cae99d.png)

**Comment by samselikoff** [comment]
I think we can't use `model:mirage` like I thought we could, thanks for reporting this. I'll update the factory name.

**Comment by samselikoff** [comment]
563074a4e8d23f93b0ec7ae0737854fac0c10983 closes

**Comment by JoshSmith** [comment]
This issue still seems to exit for me. I'm on beta3 and only removing Mirage altogether fixes this. I've even blown away git repo and recloned to make absolutely sure it wasn't npm cache issues or anything. My `node_modules` for Mirage looked correct with the right file changes, but each time I saw the `:` for factories when debugged into the `reopenClass` call.

**Comment by samselikoff** [comment]
Hmm... no way of knowing what it is regarding this issue, because none of the blueprints have a `:` in the name anymore. I wonder if you could produce a simple test case in a new ember app?
