### ISSUE TITLE
Cannot read property 'where' of undefined

### ISSUE THREAD

**Issue by Jordan4jc** [samselikoff/ember-cli-mirage#396]
My mirage config works fine in development but in testing I am getting this error in the console.
```
Mirage: Your handler for the url /api/items?auction_id=3714 threw an error: Cannot read property 'where' of undefined TypeError: Cannot read property 'where' of undefined
    at FunctionRouteHandler.userFunction (http://localhost:4200/assets/bidr.js:1149:31)
    at FunctionRouteHandler.handle (http://localhost:4200/assets/vendor.js:148255:21)
    at RouteHandler._getMirageResponseForRequest (http://localhost:4200/assets/vendor.js:148141:30)
    at RouteHandler.handle (http://localhost:4200/assets/vendor.js:148113:35)
    at Object.handler (http://localhost:4200/assets/vendor.js:149516:43)
    at Object.handleRequest (http://localhost:4200/assets/vendor.js:71011:44)
    at Object.send (http://localhost:4200/assets/vendor.js:70849:17)
    at Object.send (http://localhost:4200/assets/vendor.js:9866:10)
    at Function.jQuery.extend.ajax (http://localhost:4200/assets/vendor.js:9417:15)
    at http://localhost:4200/assets/vendor.js:127821:19
```
The config for this looks like this
```
this.get('/items', function(db,request){
    return {items: db.items.where({auction_id: request.queryParams.auction_id})};
});
```
This error is only happening in my test runner and not in development

**Comment by samselikoff** [comment]
Hm, and you have an Item factory defined?

**Comment by Jordan4jc** [comment]
I switched to using fixtures so it was easier to develop with the peace of mind I knew what I should be seeing.

I have an `items.js` fixture that has the typical setup.

**Comment by samselikoff** [comment]
Great. This route handler should also work given a `/factories/item.js` file. Closing this issue for now, please let me know if you still need help!
