### ISSUE TITLE
Ember inspector erroring in factoryFor with model:mirage/models

### ISSUE THREAD

**Issue by joshsmith** [samselikoff/ember-cli-mirage#551]
The Ember Inspector crashes when using `0.2.0-beta.3`.

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: injectedFactory.reopenClass is not a function
Stack trace: TypeError: injectedFactory.reopenClass is not a function
    at factoryFor (http://localhost:4200/assets/vendor-496907f2e898fc4eb360b50ce464b17c.js:12059:23)
    at Object.Container.lookupFactory (http://localhost:4200/assets/vendor-496907f2e898fc4eb360b50ce464b17c.js:11937:14)
    at exports.default._emberRuntimeSystemObject.default.extend._nameToClass (http://localhost:4200/assets/vendor-496907f2e898fc4eb360b50ce464b17c.js:16659:31)
    at http://localhost:4200/assets/vendor-496907f2e898fc4eb360b50ce464b17c.js:16856:25
    at Array.map (native)
    at exports.default._emberRuntimeSystemObject.default.extend.getModelTypes (http://localhost:4200/assets/vendor-496907f2e898fc4eb360b50ce464b17c.js:16854:56)
    at exports.default._emberRuntimeSystemObject.default.extend.watchModelTypes (http://localhost:4200/assets/vendor-496907f2e898fc4eb360b50ce464b17c.js:16634:29)
    at getModelTypes (<anonymous>:844:55)
    at Object.apply (http://localhost:4200/assets/vendor-496907f2e898fc4eb360b50ce464b17c.js:34201:18)
    at Object.sendEvent (http://localhost:4200/assets/vendor-496907f2e898fc4eb360b50ce464b17c.js:27753:28)
```

You can reproduce this by pulling down https://github.com/code-corps/code-corps-ember (you'll also need the API as index is served over redis: https://github.com/code-corps/code-corps-api). I get this error on any route I visit.

Let me know if you have trouble pulling down my project to reproduce.

**Comment by samselikoff** [comment]
With redis, the api and the Ember app, there are a lot of moving pieces here. Have you tried reproducing the bug in a fresh Ember app?

**Comment by JoshSmith** [comment]
@samselikoff I haven't tried reproducing yet. I'm on OSX with Chrome.

I'm updating to beta4 and I'll see if anything changes.

**Comment by JoshSmith** [comment]
@samselikoff was able to reproduce. This won't affect me going forward, but it's still a quirky little bug.

https://github.com/JoshSmith/ember-cli-mirage-bug

The problem arises when you create a Mirage model with the filename `model.js`. Definitely weird.

**Comment by JoshSmith** [comment]
You'll need to click into the "data" tab to see the error, I think.

**Comment by samselikoff** [comment]
Bizarre - and thank you so much for tracking this down. I'll prioritize it against my current work.

**Comment by samselikoff** [comment]
Closing due to inactivity, perhaps this has been fixed with later updates in inspector & mirage? Please reopen if it's still an issue.

**Comment by JoshSmith** [comment]
@samselikoff to be honest I had not checked since I was waiting on triage here.

**Comment by samselikoff** [comment]
Ok will re-look into this after I finish cleaning through the rest of the issues.

**Comment by JoshSmith** [comment]
No worries! I think it's probably as simple as using the repo I created to reproduce and upping to latest.

**Comment by samselikoff** [comment]
Just tried to repo in latest versions of things and it seems to be fixed 👍
