### ISSUE TITLE
Throw Errors instead of Strings

### ISSUE THREAD

**Issue by Turbo87** [samselikoff/ember-cli-mirage#559]
It seems that this addon is currently throwing plain strings instead of `Error` instances. I've noticed this because using it with `mocha` warned me like this: 

```
Error: the string "You're trying to create a sensor, but no factory for this type was found" was thrown, throw an Error :)
    at Runner.fail (assets/test-support.js:6477:11)
    at assets/test-support.js:6751:18
    at done (assets/test-support.js:6205:5)
    at Test.Runnable.run (assets/test-support.js:6228:7)
    at Runner.runTest (assets/test-support.js:6661:10)
    at assets/test-support.js:6744:12
    at next (assets/test-support.js:6586:14)
    at assets/test-support.js:6596:7
    at next (assets/test-support.js:6531:23)
    at assets/test-support.js:6558:7
```

Is there a reason for throwing strings over proper errors?

**Comment by Turbo87** [comment]
note that this was with the current stable version (v0.1.11) and from the source code it looks like the master branch is throwing proper errors now.
