### ISSUE TITLE
Expected the primary data returned by the serializer for a `queryRecord` response to be a single object but instead it was an array

### ISSUE THREAD

**Issue by fknoll** [samselikoff/ember-cli-mirage#771]
I am using newest production releases:
```
"ember-cli": "^2.6.0"
”ember”: "v2.6.0"
"ember-data": "^2.6.0"
"ember-cli-mirage": "^0.2.0"
```
Using the ```store.queryRecord()``` method in a route:
```
import Ember from 'ember';
export default Ember.Route.extend({
  model() {
    return this.store.queryRecord('user', {username: 'MODO'}); // 25, MODO
  }
});
```
I get this error:
```
Error: Assertion Failed: Expected the primary data returned by the serializer for a `queryRecord` response to be a single object but instead it was an array.
```
Replacing the ```store.queryRecord() ``` method with the ```store.findRecord()``` method:
```
    return this.store.findRecord('user', '25'); // 25, MODO
```
Then everything works fine!?

Is this a problem with Mirage?
With Ember Data?
Or, is it me who have misunderstood something?

**Comment by samselikoff** [comment]
What does your `mirage/config.js` look like for this route?

**Comment by fknoll** [comment]
@samselikoff - Thank you for returning to me on this issue.

This is the content of my ```mirage/config.js```:

```
export default function() {

  this.get('/users');
  this.get('users/:id');

};
```
Yes, I am speculating which one of those two route definitions is serving ```this.store.queryRecord()```  and which one is serving ```this.store.findRecord()``` ? 

Am I missing one of more definitions? Do I need additional route definitions to support query parameters like filter, sort and page?

**Comment by samselikoff** [comment]
I'm pretty sure `queryRecord` expects an array response. Can you paste in your `console.log` response to this request? Also, what adapter are you using? Do you have a Mirage serializer specified?

**Comment by fknoll** [comment]
I am completely default in relation to Mirage 0.2.0.

This is the content of  my ```app\adapters\application.js``` file:
```
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
});
```
I have no adapter definitions in my mirage folder.

This is the content of  my ```mirage/serializers/application.js``` file:
```
import { JSONAPISerializer } from 'ember-cli-mirage';

export default JSONAPISerializer.extend({
});
```

This is my ```console.log``` response:
```
DEBUG: -------------------------------
ember.debug.js:6529DEBUG: Ember      : 2.6.0
ember.debug.js:6529DEBUG: Ember Data : 2.6.0
ember.debug.js:6529DEBUG: jQuery     : 2.2.4
ember.debug.js:6529DEBUG: -------------------------------
server.js:66 Successful request: GET /login-users
server.js:77 Object {data: Array[1]}
ember.debug.js:27773 Error while processing route: user Assertion Failed: Expected the primary data returned by the serializer for a `queryRecord` response to be a single object but instead it was an array. Error: Assertion Failed: Expected the primary data returned by the serializer for a `queryRecord` response to be a single object but instead it was an array.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:25787:21)
    at assert (http://localhost:4200/assets/vendor.js:16629:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:25551:34)
    at assert (http://localhost:4200/assets/vendor.js:124529:37)
    at Class.normalizeQueryRecordResponse (http://localhost:4200/assets/vendor.js:138181:41)
    at Class.superWrapper [as normalizeQueryRecordResponse] (http://localhost:4200/assets/vendor.js:32413:22)
    at Class.normalizeResponse (http://localhost:4200/assets/vendor.js:138719:52)
    at normalizeResponseHelper (http://localhost:4200/assets/vendor.js:132206:41)
    at http://localhost:4200/assets/vendor.js:132114:98logError @ ember.debug.js:27773error @ ember.debug.js:27716triggerEvent @ ember.debug.js:27832trigger @ ember.debug.js:51127trigger @ ember.debug.js:50940(anonymous function) @ ember.debug.js:50748tryCatch @ ember.debug.js:51460invokeCallback @ ember.debug.js:51475publish @ ember.debug.js:51443publishRejection @ ember.debug.js:51378(anonymous function) @ ember.debug.js:31345invoke @ ember.debug.js:333flush @ ember.debug.js:397flush @ ember.debug.js:205end @ ember.debug.js:560run @ ember.debug.js:682join @ ember.debug.js:702run.join @ ember.debug.js:20306hash.success @ rest.js:901fire @ jquery.js:3187fireWith @ jquery.js:3317done @ jquery.js:8757(anonymous function) @ jquery.js:9123(anonymous function) @ fake_xml_http_request.js:137dispatchEvent @ fake_xml_http_request.js:181_readyStateChange @ fake_xml_http_request.js:381_setResponseBody @ fake_xml_http_request.js:445respond @ fake_xml_http_request.js:466(anonymous function) @ pretender.js:335resolve @ pretender.js:372(anonymous function) @ pretender.js:363
ember.debug.js:31387 Error: Assertion Failed: Expected the primary data returned by the serializer for a `queryRecord` response to be a single object but instead it was an array.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:25787:21)
    at assert (http://localhost:4200/assets/vendor.js:16629:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:25551:34)
    at assert (http://localhost:4200/assets/vendor.js:124529:37)
    at Class.normalizeQueryRecordResponse (http://localhost:4200/assets/vendor.js:138181:41)
    at Class.superWrapper [as normalizeQueryRecordResponse] (http://localhost:4200/assets/vendor.js:32413:22)
    at Class.normalizeResponse (http://localhost:4200/assets/vendor.js:138719:52)
    at normalizeResponseHelper (http://localhost:4200/assets/vendor.js:132206:41)
    at http://localhost:4200/assets/vendor.js:132114:98onerrorDefault @ ember.debug.js:31387trigger @ ember.debug.js:52130(anonymous function) @ ember.debug.js:53381invoke @ ember.debug.js:333flush @ ember.debug.js:397flush @ ember.debug.js:205end @ ember.debug.js:560run @ ember.debug.js:682join @ ember.debug.js:702run.join @ ember.debug.js:20306hash.success @ rest.js:901fire @ jquery.js:3187fireWith @ jquery.js:3317done @ jquery.js:8757(anonymous function) @ jquery.js:9123(anonymous function) @ fake_xml_http_request.js:137dispatchEvent @ fake_xml_http_request.js:181_readyStateChange @ fake_xml_http_request.js:381_setResponseBody @ fake_xml_http_request.js:445respond @ fake_xml_http_request.js:466(anonymous function) @ pretender.js:335resolve @ pretender.js:372(anonymous function) @ pretender.js:363
server.js:66 Successful request: GET /users?username=MODO
server.js:77 Object {data: Array[3]}
```

Seems like using ```store.queryRecord('user', {username: 'MODO'})``` translates into ```GET /users?username=MODO```.

The returned model is an array with all three instances/objects of the user model - not only the single instance/object ```username=MODO``` requested.

**Comment by samselikoff** [comment]
Looks like `queryRecord` expects a single object in response (instead of an array), so you'll need to do something like

```js
this.get('/users', (schema, request) => {
    return schema.users.where(u => u.username === request.queryParams.username)[0];
});
```

Does that make sense?

**Comment by fknoll** [comment]
Yes, your response definitely makes sense, thank you!

My problem is, that in my application I use all of the methods ```store.findAll('myModel')```, ```store.query('myModel', {x: 'a', y: 'b'})``` and ```store.queryRecord('myModel', {x: 'a', y: 'b', z: 'c'})```.

In addition, in my application the mix of query parameters varies. You example is hardcoded with one specific query parameter?

How do I setup Mirage to distinguish between those three scenarios, where ```store.findAll()``` and ```store.query()``` expects an array and ```store.queryRecord()``` expects an object?

I guess, I will have to get rid of using ```store.queryRecord()```, and instead extract the single returned object from the returned array, like this
```
  model() {
    return that.store.query('myModel', {x: 'a', y: 'b', z: 'b'})
    .then(function(myModelArray) {
      return myModelArray.get('firstObject');
    });
  }
```

Supported in ```mirage/config.js``` by:
```
  this.get('/my-models', (schema, request) => {
    return schema.myModels.where(request.queryParams);
  });
```

**Comment by samselikoff** [comment]
Yes, I think this makes the most sense. Looking at the [docs for DS.Store](http://emberjs.com/api/data/classes/DS.Store.html#method_queryRecord) it says 

> Note: the primary use case for store.queryRecord is when a single record is queried and the id is not kown beforehand. In all other cases store.query and using the first item of the array is likely the preferred way:

so I think what you said is correct.
