### ISSUE TITLE
Could not find module `web/initializers/ember-cli-mirage`

### ISSUE THREAD

**Issue by ssurana2** [samselikoff/ember-cli-mirage#900]
Tried doing as mentioned in http://www.ember-cli-mirage.com/docs/v0.2.x/manually-starting-mirage/ but still getting the below error

```
Error: Could not find module `web/initializers/ember-cli-mirage` imported from `web/tests/helpers/setup-mirage-for-integration`
    at missingModule (http://localhost:7357/assets/vendor.js:228:11)
    at findModule (http://localhost:7357/assets/vendor.js:239:17)
    at Module.findDeps (http://localhost:7357/assets/vendor.js:179:24)
    at findModule (http://localhost:7357/assets/vendor.js:242:11)
    at Module.findDeps (http://localhost:7357/assets/vendor.js:179:24)
    at findModule (http://localhost:7357/assets/vendor.js:242:11)
    at requireModule (http://localhost:7357/assets/vendor.js:29:15)
    at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:67:9)
    at Object.loadModules (http://localhost:7357/assets/test-loader.js:58:18)
    at Function.TestLoader.load (http://localhost:7357/assets/test-loader.js:89:24)
```

Mirage version: 0.2.2
Ember Version: 2.4.6
Ember cli version: 2.5.0

**Comment by ssurana2** [comment]
Don't know how it got resolved, but after uninstalling and reinstalling the package, the issue got resolved. So closing the issue
